### PR TITLE
Add messages.deleteFromUser

### PR DESCRIPTION
**Pull request by damianfral**

### CODE REVIEW

**Comment by iainelder** [comment]
This is for CH10693.

https://app.clubhouse.io/feeld/story/10693/gdpr-fix-script-to-delete-layer-messages

**Comment by damianfral** [comment]
@iainelder, I executed the extraction script, then deletion scripts and checked that after deletion, sent messages are not returned in extracted messages anymore.

```
λ coffee runner.coffee layer/extract_all_data.coffee d=production id 581098a97d2a68cd030a35b1
  fld:scripts/runner process.env.DEBUG: fld:scripts*,fld:fld_modules/script_helpers* +0ms
  fld:fld_modules/script_helpers/runner_impl script_path layer/extract_all_data.coffee +0ms
  fld:fld_modules/script_helpers/runner_impl named { d: 'production' } +3ms
  fld:fld_modules/script_helpers/runner_impl remaining [ 'id', '581098a97d2a68cd030a35b1' ] +4ms
  fld:fld_modules/script_helpers/runner_impl Loading script at path: layer/extract_all_data.coffee +2ms
  fld:fld_modules/script_helpers/runner_impl script_opt { id: '581098a97d2a68cd030a35b1' } +108ms
  fld:fld_modules/script_helpers/execute_self_described options { id: 581098a97d2a68cd030a35b1 } +0ms
  fld:fld_modules/script_helpers/execute_with_services Services: [ 'db', 'layer' ] +0ms
  fld:fld_modules/script_helpers/execute_with_services environments: [ 'production' ] +2ms
  fld:fld_modules/script_helpers/execute_with_services Script options:  { id: 581098a97d2a68cd030a35b1 } +2ms
  fld:fld_modules/script_helpers/prepare_environment Starting services for undefined ... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services started. +5s
  fld:fld_modules/script_helpers/execute_with_services Runnig script ... +0ms
  fld:fld_modules/script_helpers/execute_with_services Script finished! +1s
  fld:fld_modules/script_helpers/execute_with_services Script response:
  fld:fld_modules/script_helpers/execute_with_services  [
  [
    {
      "body": [
        "hi"
      ],
      "sent_at": "2017-09-28T15:17:37.859Z"
    }
  ],
  [
    {
      "body": [
        "hi"
      ],
      "sent_at": "2017-11-27T12:12:10.280Z"
    }
  ]
] +0ms
  fld:fld_modules/script_helpers/execute_with_services Stopping services... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services stopped. +22ms
```

```
coffee runner.coffee layer/delete_sent_messages.coffee  d=production id 581098a97d2a68cd030a35b1
  fld:scripts/runner process.env.DEBUG: fld:scripts*,fld:fld_modules/script_helpers* +0ms
  fld:fld_modules/script_helpers/runner_impl script_path layer/delete_sent_messages.coffee +0ms
  fld:fld_modules/script_helpers/runner_impl named { d: 'production' } +8ms
  fld:fld_modules/script_helpers/runner_impl remaining [ 'id', '581098a97d2a68cd030a35b1' ] +18ms
  fld:fld_modules/script_helpers/runner_impl Loading script at path: layer/delete_sent_messages.coffee +6ms
  fld:fld_modules/script_helpers/runner_impl script_opt { id: '581098a97d2a68cd030a35b1' } +182ms
  fld:fld_modules/script_helpers/execute_self_described options { id: 581098a97d2a68cd030a35b1, sort_by: 'last_message' } +0ms
  fld:fld_modules/script_helpers/execute_with_services Services: [ 'db', 'layer' ] +0ms
  fld:fld_modules/script_helpers/execute_with_services environments: [ 'production' ] +2ms
  fld:fld_modules/script_helpers/execute_with_services Script options:  { id: 581098a97d2a68cd030a35b1, sort_by: 'last_message' } +6ms
  fld:fld_modules/script_helpers/prepare_environment Starting services for undefined ... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services started. +5s
  fld:fld_modules/script_helpers/execute_with_services Runnig script ... +1ms
[ 'send',
  'sendDedupe',
  'sendTextFromUser',
  'sendTextFromName',
  'getAll',
  'getAllFromUser',
  'deleteFromUser',
  'getFromUser',
  'sendAsync',
  'sendDedupeAsync',
  'sendTextFromUserAsync',
  'sendTextFromNameAsync',
  'getAllAsync',
  'getAllFromUserAsync',
  'deleteFromUserAsync',
  'getFromUserAsync' ]
[ 'send',
  'sendDedupe',
  'sendTextFromUser',
  'sendTextFromName',
  'getAll',
  'getAllFromUser',
  'deleteFromUser',
  'getFromUser',
  'sendAsync',
  'sendDedupeAsync',
  'sendTextFromUserAsync',
  'sendTextFromNameAsync',
  'getAllAsync',
  'getAllFromUserAsync',
  'deleteFromUserAsync',
  'getFromUserAsync' ]
[[""],[""]]
  fld:fld_modules/script_helpers/execute_with_services Script finished! +2s
  fld:fld_modules/script_helpers/execute_with_services Script response:
  fld:fld_modules/script_helpers/execute_with_services  undefined +0ms
  fld:fld_modules/script_helpers/execute_with_services Stopping services... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services stopped. +8ms
```
```
λ coffee runner.coffee layer/extract_all_data.coffee d=production id 581098a97d2a68cd030a35b1
  fld:scripts/runner process.env.DEBUG: fld:scripts*,fld:fld_modules/script_helpers* +0ms
  fld:fld_modules/script_helpers/runner_impl script_path layer/extract_all_data.coffee +0ms
  fld:fld_modules/script_helpers/runner_impl named { d: 'production' } +17ms
  fld:fld_modules/script_helpers/runner_impl remaining [ 'id', '581098a97d2a68cd030a35b1' ] +26ms
  fld:fld_modules/script_helpers/runner_impl Loading script at path: layer/extract_all_data.coffee +5ms
  fld:fld_modules/script_helpers/runner_impl script_opt { id: '581098a97d2a68cd030a35b1' } +177ms
  fld:fld_modules/script_helpers/execute_self_described options { id: 581098a97d2a68cd030a35b1 } +0ms
  fld:fld_modules/script_helpers/execute_with_services Services: [ 'db', 'layer' ] +0ms
  fld:fld_modules/script_helpers/execute_with_services environments: [ 'production' ] +1ms
  fld:fld_modules/script_helpers/execute_with_services Script options:  { id: 581098a97d2a68cd030a35b1 } +0ms
  fld:fld_modules/script_helpers/prepare_environment Starting services for undefined ... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services started. +6s
  fld:fld_modules/script_helpers/execute_with_services Runnig script ... +0ms
  fld:fld_modules/script_helpers/execute_with_services Script finished! +1s
  fld:fld_modules/script_helpers/execute_with_services Script response:
  fld:fld_modules/script_helpers/execute_with_services  [] +1ms
  fld:fld_modules/script_helpers/execute_with_services Stopping services... +0ms
  fld:fld_modules/script_helpers/execute_with_services Services stopped. +12ms
```

**Comment by iainelder** [comment]
I just noticed that this is a different repo from backend!

The project already [conversations.delete](has https://github.com/Feeld/node-layer-api#conversationsdeletecid-callback). Is this not enough for us?

Can we add this method to the documentation?

Should we add unit tests for this new function?

Do we execute the unit tests in our CI environment?

**Comment by damianfral** [comment]
@iainelder,

> The project already has conversations.delete. Is this not enough for us?
That's for deleting the conversation. The task said "only sent messages". 

> Can we add this method to the documentation?
Not sure what you mean. :S 

> Should we add unit tests for this new function?
  Do we execute the unit tests in our CI environment?

I wouldn't add tests for this "function", at least in this repo. The main repo is deprecated and this thing will be executed manually. :)

**Comment by iainelder** [comment]
> Can we add this method to the documentation?
>> Not sure what you mean. :S

The README for node-layer-api documents all the methods. That's how I discovered the conversations.delete method. Should we add this new method to that documentation?

> I wouldn't add tests for this "function", at least in this repo. The main repo is deprecated and this thing will be executed manually. :)

Just now I believe we can live without tests and documentation, however:

* that main repo is deprecated is even more reason to do our own testing and documentation. This is now our code. The original repo will never do it for us.
* if later we decide to call this method from an automatic process, we should test and document this function as part of the work

**Comment by damianfral** [comment]
@iainelder \
> The README for node-layer-api documents all the methods. That's how I discovered the conversations.delete method. Should we add this new method to that documentation?

Done.

**Pull request merged**
